import fs from 'fs';
import path from 'path';

const ROOT_DIR = 'Galaxies_Folder';
const OUTPUT_FILE = 'apps/affinity-viz/lore_data.ts';

function findFiles(dir, fileName, fileList = []) {
    if (!fs.existsSync(dir)) return fileList;
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat.isDirectory()) {
            findFiles(filePath, fileName, fileList);
        } else if (file === fileName) {
            fileList.push(filePath);
        }
    }
    return fileList;
}

const loreFiles = findFiles(ROOT_DIR, 'lorebook.json');
const combinedLore = {};

console.log(`Found ${loreFiles.length} lorebook files.`);

for (const file of loreFiles) {
    try {
        const content = fs.readFileSync(file, 'utf8');
        const json = JSON.parse(content);
        if (json.world_id) {
            combinedLore[json.world_id] = json;
            // console.log(`Loaded ${json.world_id} from ${file}`);
        } else {
            console.warn(`Skipping ${file}: No world_id found.`);
        }
    } catch (e) {
        console.error(`Error reading ${file}:`, e.message);
    }
}

const fileContent = `// Auto-generated by aggregate_lore.js
// Do not edit manually.
export const LORE_DATA: Record<string, any> = ${JSON.stringify(combinedLore, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Wrote ${Object.keys(combinedLore).length} worlds to ${OUTPUT_FILE}`);
